project:
  type: website
  output-dir: _site
  resources:
    - GreenEquity_HN.html

website:
  title: "A. Naya"
  description: "Environmental Data Science – Apps, Analyses & Tools"
  site-url: https://anayana.github.io
  favicon: assets/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/anayana
        aria-label: GitHub
      - icon: envelope
        href: mailto:steinchen16@posteo.de
        aria-label: E-Mail
  page-footer:
    left: "© 2026 A. Naya"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      light:
        - cosmo
        - theme.scss
        - light.scss
      dark:
        - slate
        - theme.scss
        - dark.scss
    toc: true
    toc-title: "Contents"
    code-copy: true
    code-overflow: wrap
    grid:
      body-width: 900px

lang: en
