/* Shipped catalogue: 3 trees, UEF Campus Joensuu.
   Geometry from OSM nodes 12498051519/20/21 - crown centres digitised from aerial
   imagery, not surveyed stem bases (see the note on the start screen).
   Attributes are synthetic, modelled on FLL / VTA practice. */
const TREES_DEFAULT = {
  "type": "FeatureCollection",
  "name": "tree_register_joensuu",
  "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
  "features": [
    {
      "type": "Feature", "id": 1,
      "geometry": { "type": "Point", "coordinates": [29.7454436, 62.6040424] },
      "properties": {
        "tree_id": "JNS-001",
        "osm_id": "12498051519",
        "inspector": "synthetic (demo)",
        "geometry_source": "OpenStreetMap node",
        "position_accuracy_m": 3.0,
        "species": "Betula pendula",
        "name_en": "Silver birch",
        "name_fi": "Rauduskoivu",
        "planted": 1998,
        "girth_cm": 112,
        "dbh_cm": 36,
        "height_m": 16.5,
        "crown_d_m": 8.0,
        "crown_base_m": 3.2,
        "vitality_roloff": 1,
        "crown_dieback_pct": 20,
        "damage_class": "slight",
        "stability": "adequate",
        "breakage_resistance": "adequate",
        "target_type": "path",
        "target_distance_m": 7.0,
        "traffic_safety": "adequate",
        "urgency": "next growing season",
        "cavity": "no",
        "wall_t_cm": null,
        "radius_r_cm": null,
        "tree_pit_m2": 6.0,
        "location": "Lawn, campus",
        "inspection_type": "Routine inspection",
        "last_inspection": "2025-06-12",
        "next_inspection": "2026-06-30",
        "interval_months": 12,
        "symptoms": ["c_deadwood", "t_bark"],
        "symptom_labels": ["Deadwood > 3 cm", "Bark or cambium damage"],
        "actions": ["Remove deadwood"],
        "remarks": "Slight thinning in the upper crown.",
        "history": [
          { "year": 2020, "girth_cm": 102.0, "vitality_roloff": 0, "inspection": "2020-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2021, "girth_cm": 104.0, "vitality_roloff": 0, "inspection": "2021-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2022, "girth_cm": 106.0, "vitality_roloff": 1, "inspection": "2022-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2023, "girth_cm": 108.0, "vitality_roloff": 1, "inspection": "2023-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2024, "girth_cm": 110.0, "vitality_roloff": 1, "inspection": "2024-06-15", "finding": "Routine inspection" }
        ]
      }
    },
    {
      "type": "Feature", "id": 2,
      "geometry": { "type": "Point", "coordinates": [29.7456448, 62.6040164] },
      "properties": {
        "tree_id": "JNS-002",
        "osm_id": "12498051520",
        "inspector": "synthetic (demo)",
        "geometry_source": "OpenStreetMap node",
        "position_accuracy_m": 3.0,
        "species": "Tilia cordata",
        "name_en": "Small-leaved lime",
        "name_fi": "Metsälehmus",
        "planted": 2003,
        "girth_cm": 78,
        "dbh_cm": 25,
        "height_m": 11.0,
        "crown_d_m": 6.0,
        "crown_base_m": 2.5,
        "vitality_roloff": 0,
        "crown_dieback_pct": 5,
        "damage_class": "none",
        "stability": "adequate",
        "breakage_resistance": "adequate",
        "target_type": "path",
        "target_distance_m": 9.0,
        "traffic_safety": "adequate",
        "urgency": "none",
        "cavity": "no",
        "wall_t_cm": null,
        "radius_r_cm": null,
        "tree_pit_m2": 4.5,
        "location": "Lawn, campus",
        "inspection_type": "Routine inspection",
        "last_inspection": "2025-06-12",
        "next_inspection": "2027-06-30",
        "interval_months": 24,
        "symptoms": [],
        "symptom_labels": [],
        "actions": [],
        "remarks": "Vigorous tree, nothing conspicuous.",
        "history": [
          { "year": 2020, "girth_cm": 68.0, "vitality_roloff": 0, "inspection": "2020-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2021, "girth_cm": 70.0, "vitality_roloff": 0, "inspection": "2021-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2022, "girth_cm": 72.0, "vitality_roloff": 0, "inspection": "2022-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2023, "girth_cm": 74.0, "vitality_roloff": 0, "inspection": "2023-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2024, "girth_cm": 76.0, "vitality_roloff": 0, "inspection": "2024-06-15", "finding": "Routine inspection" }
        ]
      }
    },
    {
      "type": "Feature", "id": 3,
      "geometry": { "type": "Point", "coordinates": [29.7455804, 62.6040485] },
      "properties": {
        "tree_id": "JNS-003",
        "osm_id": "12498051521",
        "inspector": "synthetic (demo)",
        "geometry_source": "OpenStreetMap node",
        "position_accuracy_m": 3.0,
        "species": "Picea abies",
        "name_en": "Norway spruce",
        "name_fi": "Kuusi",
        "planted": 1992,
        "girth_cm": 145,
        "dbh_cm": 46,
        "height_m": 19.0,
        "crown_d_m": 7.5,
        "crown_base_m": 1.8,
        "vitality_roloff": 2,
        "crown_dieback_pct": 30,
        "damage_class": "moderate",
        "stability": "restricted",
        "breakage_resistance": "adequate",
        "target_type": "path",
        "target_distance_m": 4.0,
        "traffic_safety": "restricted",
        "urgency": "3 months",
        "cavity": "no",
        "wall_t_cm": null,
        "radius_r_cm": 23,
        "tree_pit_m2": 8.0,
        "location": "Lawn, campus",
        "inspection_type": "Detailed assessment",
        "last_inspection": "2025-06-12",
        "next_inspection": "2026-03-31",
        "interval_months": 9,
        "symptoms": ["t_bleeding", "t_fungi", "c_dieback"],
        "symptom_labels": ["Resin or slime flux", "Fruiting bodies of wood-decay fungi", "Crown dieback"],
        "actions": ["Detailed assessment", "Re-inspect in 9 months"],
        "remarks": "Suspected root and butt rot. Consider a pulling test.",
        "history": [
          { "year": 2020, "girth_cm": 135.0, "vitality_roloff": 1, "inspection": "2020-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2021, "girth_cm": 137.0, "vitality_roloff": 1, "inspection": "2021-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2022, "girth_cm": 139.0, "vitality_roloff": 2, "inspection": "2022-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2023, "girth_cm": 141.0, "vitality_roloff": 2, "inspection": "2023-06-15", "finding": "Routine inspection, no findings" },
          { "year": 2024, "girth_cm": 143.0, "vitality_roloff": 2, "inspection": "2024-06-15", "finding": "Routine inspection" }
        ]
      }
    }
  ]
};
